export const stateConstants = {
  GET_ALL_STATES_REQUEST: "GET_ALL_STATES_REQUEST",
  GET_ALL_STATES_SUCCESS: "GET_ALL_STATES_SUCCESS",
  GET_ALL_STATES_FAILURE: "GET_ALL_STATES_FAILURE",
  SET_STATE: "SET_STATE",
  SET_DIST: "SET_DIST",
};

export const caseConstants = {
  GET_CASES_REQUEST: "GET_CASES_REQUEST",
  GET_CASES_SUCCESS: "GET_CASES_SUCCESS",
  GET_CASES_FAILURE: "GET_CASES_FAILURE",
};
